### PR TITLE
fixes #363, #376; gateway settings page fixes

### LINKED ISSUE #363: Improve instructions on gateway settings
- Change wording of "Take a look pocket docs"
- Make second reference at the bottom for docs a link
- Add instructions about how the whitelists need to be comma delimited

### PR DESCRIPTION
**Pull request by nymd**

### CODE REVIEW

File: frontend/src/views/Apps/GeneralSettings/GeneralSettings.js [hunk 1]
```diff
@@ -289,13 +297,18 @@ class GeneralSettings extends Component {
             <Formik>
               <Form>
                 <Form.Group>
-                  <Form.Label className="pl-4">Whitelist User agents</Form.Label>
+                  <Form.Label className="pl-4">
+                    Whitelist User-Agents
+                    <OverlayTrigger placement="top" overlay={renderTooltipWhitelistUserAgents}>
+                      <img class="tooltip-i" src={"/assets/i-circle.svg"} alt="info-action-icon" />
```
Comment (pabelnl) [inline frontend/src/views/Apps/GeneralSettings/GeneralSettings.js]: use className instead of class for react

File: frontend/src/views/Apps/GeneralSettings/GeneralSettings.js [hunk 2]
```diff
@@ -316,13 +329,18 @@ class GeneralSettings extends Component {
             <Formik>
               <Form>
                 <Form.Group>
-                  <Form.Label className="pl-4">Whitelist Origins</Form.Label>
+                  <Form.Label className="pl-4">
+                    Whitelist Origins
+                    <OverlayTrigger placement="top" overlay={renderTooltipWhitelistOrigins}>
+                      <img class="tooltip-i" src={"/assets/i-circle.svg"} alt="info-action-icon" />
```
Comment (pabelnl) [inline frontend/src/views/Apps/GeneralSettings/GeneralSettings.js]: className

**Review by pabelnl — CHANGES_REQUESTED** [review]

**Review by wgarcia4190 — APPROVED** [review]

**Review by pabelnl — APPROVED** [review]
