### PR TITLE
Fixing import duplicated nodes

### LINKED ISSUE #401: Node's importing error/issue
**Description**
Not able to import a node completely, existing node validation pops up but the node is added to the list. 

**Step by Step:**

1. Go to the node's section.
2. Click on import a node button.
3. Provide the node's keyfile and passphrase.
4. Click on continue.
5. Notice that the existing node validation is triggered. But you can still press continue again.
6. Now you can return to the node's section, and find the node imported in the node's list.
7. If you try it again, you see the node existing validation, but it adds the node again.
https://www.loom.com/share/d1c80d4ea4464f3da431f4a60267c363

**Evidence**: 
https://www.loom.com/share/514c864cd3f64185aba9d8bdbb50dd63

### PR DESCRIPTION
**Pull request by wgarcia4190**
Close #401

### CODE REVIEW

File: frontend/src/views/Apps/Import/Import.js [hunk 1]
```diff
@@ -247,10 +279,13 @@ class Import extends Component {
       ppkFileName,
       accountData,
       chains,
+      created,
     } = this.state;
 
     const {passphrase, privateKey} = this.state.data;
 
+    console.log(created);
```
Comment (nymd) [inline frontend/src/views/Apps/Import/Import.js]: console statement left in :-1:

**Review by nymd — CHANGES_REQUESTED** [review]

**Review by nymd — APPROVED** [review]

**Review by pabelnl — APPROVED** [review]
