### PR TITLE
Issue #196

### LINKED ISSUE #196: Import App
Please fix the import Journey- it is not working with PK nor PPK

once the account is created the GENERAL INFORMATION section of the page should show the account info

### PR DESCRIPTION
**Pull request by pabelnl**
Closes #196

### CODE REVIEW

File: backend/src/models/Application.js [hunk 1]
```diff
@@ -118,7 +122,41 @@ export class PocketApplication {
    */
   static createPocketApplication(applicationData) {
     const {name, owner, url, contactEmail, user, description, icon, publicPocketAccount, freeTier} = applicationData;
-    const pocketApplication = new PocketApplication(name, owner, url, contactEmail, user, description, icon, freeTier);
+    let { freeTierApplicationAccount } = applicationData
```
Comment (nymd) [inline backend/src/models/Application.js]: Push will fail without linting, pls see warnings/failures

File: backend/src/services/ApplicationService.js [hunk 2]
```diff
@@ -107,10 +110,33 @@ export default class ApplicationService extends BasePocketService {
     } catch (e) {
       networkApplication = ExtendedPocketApplication.createNetworkApplication(application.publicPocketAccount, appParameters);
     }
+    const extendedPocketApplication = ExtendedPocketApplication.createExtendedPocketApplication(application, networkApplication);
+
+    return extendedPocketApplication
```
Comment (nymd) [inline backend/src/services/ApplicationService.js]: requires ;

**Review by nymd — CHANGES_REQUESTED** [review]

**Review by wgarcia4190 — DISMISSED** [review]

**Review by nymd — DISMISSED** [review]

**Review by nymd — APPROVED** [review]

**Review by wgarcia4190 — APPROVED** [review]
