### PR TITLE
Fixing issues with Node Purchase

### LINKED ISSUE #194: Review Node Purchase
**Valitadion Power Values**
Please check if the values on the order summary are correct according to the Economics Formula values.
The values reference:
https://www.notion.so/pocketnetwork/Purchase-Final-Numbers-9b4a110f8bcb4f63918f312c474713cb

**The order Summary**
On the order Summary contains a "Balance" value which we need to subtract from the total cost of the purchased amount 

Once completed the Purchase...

**Purchase Invoice**
There is an invoice generated on which some values should be pulled from the purchase information. please, contact me for further details

**Notification**
There is an alert generated which should remain over the app detail screen until the Network confirms the node Is staked. 

** Email Notification**
Once the node is staked an email (is already created on SendGrid) should be sent to the user.

**Fix Node Detail values**

Staked tokens and Balance should be expressed on POKT, not UPOKT

Validator Power should represent the just purchased amount of relays

NETWORKS
This table should be showing the information about the stacked chains

And Service URL shout be showing the SS URL provided on the previous stake

### PR DESCRIPTION
**Pull request by wgarcia4190**
Close #194

### CODE REVIEW

File: frontend/src/core/components/Passphrase/Passphrase.js [hunk 1]
```diff
@@ -122,7 +118,8 @@ class Passphrase extends Component {
    * Handles account creation and next steps
    * @abstract
    */
-  async createAccount() {}
+  async createAccount() {
+  }
```
Comment (pabelnl) [inline frontend/src/core/components/Passphrase/Passphrase.js:122]: Why the empty function?

File: frontend/src/views/Nodes/NodeDetail/NodeDetail.js [hunk 2]
```diff
@@ -277,16 +289,16 @@ class NodeDetail extends Component {
...
-        </p>
-      </ValidateKeys>
+        {/* eslint-disable-next-line react/prop-types */}
+        <ValidateKeys handleBreadcrumbs={this.props.onBreadCrumbChange}
+                      breadcrumbs={breadcrumbs}
+                      address={address} handleAfterValidate={handleFunc}>
+          <h1>Verify private key</h1>
+          <p className="validate-text">
+            Please import your account credentials before sending the Transaction.
+            Be aware that this Transaction has a 0,1 POKT fee cost.
```
Comment (pabelnl) [inline frontend/src/views/Nodes/NodeDetail/NodeDetail.js]: Will be good to use `0.1` instead of `0,1`, the dot is important

**Review by pabelnl — CHANGES_REQUESTED** [review]

File: frontend/src/core/components/Passphrase/Passphrase.js (hunk 1 above)
Comment (wgarcia4190) [reply frontend/src/core/components/Passphrase/Passphrase.js:122]: it is empty because it is an "abstract function". The Passphrase file is used as parent of other objects.

**Review by pabelnl — DISMISSED** [review]

**Review by nymd — APPROVED** [review]

**Review by pabelnl — APPROVED** [review]
