### PR TITLE
Multiple fixes

### LINKED ISSUE #453: Landing page- Welcome message
On https://dashboard.testnet.pokt.network/
The welcome message should be: This tool provides a simple way to interact, purchase, and stake with Pocket Network, using real-time network information to manage app and nodes.

This should be erased from the home page welcome message container

### PR DESCRIPTION
**Pull request by pabelnl**
Closes #453 #454 #455 #460

### CODE REVIEW

**Review by wgarcia4190 — DISMISSED** [review]

File: frontend/src/core/components/DefaultLayout/AppNavbar/AppNavbar.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ class AppNavbar extends Component {
     return (
       <Row className="app-navbar" noGutters>
         <map name="workmap">
-          <area target="_blank" shape="rect" coords="0,11,115,65" alt="Pocket" href="http://www.pokt.network" />
+          <area target="_blank" shape="rect" coords="0,11,115,65" alt="Pocket" href="http://pokt.network" />
```
Comment (nymd) [inline frontend/src/core/components/DefaultLayout/AppNavbar/AppNavbar.js]: this should almost certainly be https, right?

**Review by nymd — CHANGES_REQUESTED** [review]

**Review by nymd — APPROVED** [review]

**Review by wgarcia4190 — APPROVED** [review]
